name: Test Alpacon WebSH Action

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-basic-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Alpacon CLI
        uses: alpacax/alpacon-setup-action@v1.0.0

      - name: Test Basic Command
        uses: ./
        with:
          workspace-url: ${{ secrets.TEST_ALPACON_WORKSPACE_URL }}
          api-token: ${{ secrets.TEST_ALPACON_API_TOKEN }}
          target: ${{ secrets.TEST_ALPACON_SERVER_NAME }}
          script: echo "Hello from remote server"

  test-root-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Alpacon CLI
        uses: alpacax/alpacon-setup-action@v1.0.0

      - name: Test Root Command
        uses: ./
        with:
          workspace-url: ${{ secrets.TEST_ALPACON_WORKSPACE_URL }}
          api-token: ${{ secrets.TEST_ALPACON_API_TOKEN }}
          target: ${{ secrets.TEST_ALPACON_SERVER_NAME }}
          script: |
            whoami
            ls /root
          as-root: true

  test-multiline-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Alpacon CLI
        uses: alpacax/alpacon-setup-action@v1.0.0

      - name: Test Multi-line Script
        uses: ./
        with:
          workspace-url: ${{ secrets.TEST_ALPACON_WORKSPACE_URL }}
          api-token: ${{ secrets.TEST_ALPACON_API_TOKEN }}
          target: ${{ secrets.TEST_ALPACON_SERVER_NAME }}
          script: |
            echo "=== Multi-line Script Test ==="
            echo "Command 1"
            echo "Command 2 -> Date: $(date)"
            echo "Script execution completed successfully"